### ISSUE TITLE
trouble installing Pillow on s4

### ISSUE THREAD

**Issue by johnjung** [johnjung/iiif_tools#11]
I'm not able to install Pillow on s4. Here's the command I'm using:

pip install --proxy http://jej@torus.lib.uchicago.edu:8080 Pillow

And here is the error log that's generated:

[error_log.txt](https://github.com/johnjung/iiif_tools/files/4017216/error_log.txt)

The error log contains the following line: "The headers or library files could not be found for jpeg, a required dependency when compiling Pillow from source."

Do we need to install jpeg onto this machine via pkg before installing Pillow?

**Comment by fseatonuc** [comment]
I think you may be correct.  I'd have to defer to Peggy on this one, though, as she handles the package management on that machine.

**Comment by johnjung** [comment]
Thank you, Fred- that sounds good. I'll send her a link to this issue.

**Comment by johnjung** [comment]
This is now resolved. Thank you!
