### ISSUE TITLE
Need permissions to upgrade Loris

### ISSUE THREAD

**Issue by johnjung** [johnjung/iiif_tools#12]
According to the issue https://github.com/loris-imageserver/loris/issues/435, 

I need to edit the following file:
/data/red/loris_fakeroot/var/www/loris2/loris2.wsgi

However, that file is currently owned by the user and group "loris". Is it possible for me to be able to edit these files, or should I request all edits through sys-admin?

**Comment by fseatonuc** [comment]
Added permission to run a shell as the loris user via sudo:
`IIIF IIIFHOSTS=/usr/local/sbin/apachectl, (loris:loris) ALL
`

**Comment by johnjung** [comment]
This is now resolved. Thank you!
